services:
    _defaults:
        autowire: true
        autoconfigure: true

    Synolia\SyliusMailTesterPlugin\:
        resource: '../../*'
        exclude: '../../{Fixture,SynoliaSyliusMailTesterPlugin.php}'
