services:
    _defaults:
        autowire: true
        autoconfigure: true

    Synolia\SyliusMailTesterPlugin\:
        resource: '../src/*'
        exclude: '../src/{Fixture,SynoliaSyliusMailTesterPlugin.php}'
