sylius_twig_hooks:
    hooks:
        'synolia.sylius_admin.mailtester':
            sidebar:
                template: '@SyliusAdmin/shared/crud/common/sidebar.html.twig'
                priority: 200
            navbar:
                template: '@SyliusAdmin/shared/crud/common/navbar.html.twig'
                priority: 100
            content:
                template: '@SyliusAdmin/shared/crud/common/content.html.twig'
                priority: 0
        'synolia.sylius_admin.mailtester.content':
            flashes:
                template: '@SyliusAdmin/shared/crud/common/content/flashes.html.twig'
                priority: 400
            header:
                template: '@SyliusAdmin/shared/crud/common/content/header.html.twig'
                priority: 300
            form:
                template: '@SynoliaSyliusMailTesterPlugin/admin/mailtester/content/form.html.twig'
                priority: 200
            footer:
                template: '@SyliusAdmin/shared/crud/common/content/footer.html.twig'
                priority: 100
        'synolia.sylius_admin.mailtester.content.header':
            breadcrumbs:
                template: '@SynoliaSyliusMailTesterPlugin/admin/mailtester/content/header/breadcrumbs.html.twig'
                priority: 100
            title_block:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block.html.twig'
                priority: 0
        'synolia.sylius_admin.mailtester.content.header.title_block':
            title:
                template: '@SyliusAdmin/shared/crud/common/content/header/title_block/title.html.twig'
                configuration:
                    title: 'sylius.menu.admin.main.configuration.mail_tester'
                priority: 100